# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:1.24.0"

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
#before_script:
#- apt-get update -yqq
#- apt-get install -yqq --no-install-recommends build-essential

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  
stages:
  - test
  - build

# Build the application
build:release:nightly:
  image: rustlang/rust:nightly
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo +nightly build --release
  cache:
    paths:
      - cargo/
      - target/
  only:
    - master
    - tags
    - triggers
    - schedules
  artifacts:
    paths:
      - target/release/nb
    expire_in: 1 week

# Use cargo to test the project
# test:cargo:stable:
#   image: rust:1.24.0
#   stage: test
#   script:
#   - rustc --version && cargo --version      # Print version info for debugging
#   - cargo test --all --jobs 1 --verbose -- --nocapture
  
test:cargo:nightly:
  image: rustlang/rust:nightly
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo +nightly test --all --jobs 1 --verbose -- --nocapture
