[package]
name = "nb-parser"
version = "0.1.0"
authors = ["Nicolas Berbiche"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
unicode-segmentation = "1.2.0"
itertools = "0.7.6"
phf = "0.7.21"
phf_macros = "0.7.21"
